version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: books-mysql
      working_dir: /application
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - .:/application
        - ./phpdocker/mysql:/var/lib/mysql:rw
      environment:
        - MYSQL_ROOT_PASSWORD=123
        - MYSQL_DATABASE=app
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=123
      ports:
        - "3002:3306"

    webserver:
      image: nginx:alpine
      container_name: books-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "3000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: books-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

    composer:
      build: phpdocker/composer
      container_name: books-composer
      working_dir: /application
      volumes:
        - .:/application
